name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal reproducible steps
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
