name: Feature request
description: Propose a new task/capability
title: "[Feature]: "
labels: [enhancement]
body:
  - type: input
    id: task_id
    attributes:
      label: Proposed task ID
      placeholder: pr_summarize
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What user outcome does this task deliver?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is done?
    validations:
      required: true
