from typing import TypeVar

from pydantic import BaseModel

from infra.llm.chains import CommentNormChain

ModelT = TypeVar("ModelT", bound=BaseModel)


class FakeAdapter:
    def __init__(self) -> None:
        self.last_prompt = ""

    def invoke_structured(self, prompt: str, schema: type[ModelT]) -> ModelT:
        self.last_prompt = prompt
        return schema.model_validate({"comment_text": "# generated by llm"})


def test_comment_norm_chain_renders_prompt() -> None:
    adapter = FakeAdapter()
    chain = CommentNormChain(adapter)

    output = chain.run(
        task_goal="Append a useful comment",
        target_file="demo.py",
    )

    assert output.comment_text == "# generated by llm"
    assert "Append a useful comment" in adapter.last_prompt
    assert "demo.py" in adapter.last_prompt
