from pathlib import Path
from typing import Any, cast

from infra.llm.schema import CommentNormOutput
from tasks.handlers.append_hello_agent_comment import AppendHelloAgentCommentHandler
from tasks.registry import TaskRegistry, TaskSpec


class FakeChain:
    def __init__(self, text: str) -> None:
        self._text = text

    def run(self, *, task_goal: str, target_file: str) -> CommentNormOutput:
        del task_goal, target_file
        return CommentNormOutput(comment_text=self._text)


def _spec() -> TaskSpec:
    return TaskRegistry(Path("configs/tasks")).get("append_hello_agent_comment")


def test_handler_uses_fallback_when_llm_disabled(tmp_path: Path) -> None:
    target = tmp_path / "demo.py"
    target.write_text("print('x')\n", encoding="utf-8")
    handler = AppendHelloAgentCommentHandler()
    spec = _spec()

    payload, llm_error, fatal_error = handler.preprocess_with_llm(
        payload={"target_file": str(target)},
        spec=spec,
        llm_enabled=False,
        llm_fallback_to_rules=True,
        comment_chain=None,
    )
    assert llm_error is None
    assert fatal_error is None

    result = handler.execute(payload, spec)

    assert result["changed_file"] == str(target)
    assert "p4agent fallback" in target.read_text(encoding="utf-8")


def test_handler_uses_llm_text_when_available(tmp_path: Path) -> None:
    target = tmp_path / "demo.py"
    target.write_text("print('x')\n", encoding="utf-8")
    handler = AppendHelloAgentCommentHandler()
    spec = _spec()

    payload, llm_error, fatal_error = handler.preprocess_with_llm(
        payload={"target_file": str(target)},
        spec=spec,
        llm_enabled=True,
        llm_fallback_to_rules=True,
        comment_chain=cast(Any, FakeChain("# generated by llm")),
    )

    assert llm_error is None
    assert fatal_error is None
    result = handler.execute(payload, spec)

    assert result["appended_text"] == "# generated by llm"


def test_handler_can_block_when_llm_missing(tmp_path: Path) -> None:
    target = tmp_path / "demo.py"
    target.write_text("print('x')\n", encoding="utf-8")
    handler = AppendHelloAgentCommentHandler()
    spec = _spec()

    _, llm_error, fatal_error = handler.preprocess_with_llm(
        payload={"target_file": str(target)},
        spec=spec,
        llm_enabled=True,
        llm_fallback_to_rules=False,
        comment_chain=None,
    )

    assert llm_error is not None
    assert fatal_error is not None
